### ISSUE TITLE
Assigning an "emptyList()" to KtMutableList variable produces an error

### ISSUE THREAD

**Issue by dimsuz** [passsy/kt.dart#107]
Thanks for a great library! Using dart:collections after kotlin is painful, thanks god there's something to smooth it out :)

I just started to transition my code to this lib and wrote this:

```dart
  final KtMutableList<String> _digits = emptyList(); // also tried emptyList<String>()
```
It produces the following _runtime_ error:

```
type 'EmptyList<dynamic>' is not a subtype of type 'KtMutableList<String>'
```
(or `EmptyList<String>` if I use an explicit version: `emptyList<String>()`)

I'm not sure if this is a bug in a library or something I don't know about Dart's generics...
I checked and `KtMutableList` implements `KtList` so I don't see why this assignment should be a problem.

**Comment by passsy** [comment]
That's expected. You can't assign a `KtList` (immutable) to a `KtMutableList`. The `KtList` doesn't have methods like `add(T)` which are required by the `KtMutableList` interface. `KtList` is not a `KtMutableList`.

```dart
  // works
  final KtList<String> immutableList = KtMutableList.empty();
  
  // doesn't work
  final KtMutableList<String> mutableList = KtList.empty();
```

The real question is: Why does this code result in a runtime crash and not a compile-time error?
Dart supports `implicit-casts`, here an implicit downcast. This is a leftover from Dart1 and [will be removed when NonNullable Types land in Dart](https://github.com/dart-lang/sdk/issues/31410) (~2.6).

### Workaround

You can already disable implicit casts in your `analysis_options.yaml` and the analyzer will report this error correctly. This will become the default in future dart versions.

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

```
error: A value of type 'KtList' can't be assigned to a variable of type 'KtMutableList<String>'. (invalid_assignment at [kt_dart] example/main.dart:8)
```

### Correct code

For completeness, this is the correct code to initialize an empty `KtMutableList`.

```dart
  final KtMutableList<String> mutableList1 = mutableListOf();
  final KtMutableList<String> mutableList2 = KtMutableList.empty();
```

**Comment by dimsuz** [comment]
Thank you very much for thorough explanation, it helped be learn new things not only about `kt.dart`, but also about Dart :) Cheers!
