### ISSUE TITLE
compareBy{ }.thenBy{ }

### ISSUE THREAD

**Issue by bernaferrari** [passsy/kt.dart#108]
I'm loving your project, but I had some issues like using groupBy and converting the following into kt.dart. 

```kotlin 
items.sortWith(compareBy<DictionaryItem> { it.gifPrio }.thenBy { it.gifSubPrio }.thenBy { it.gifTitle })
```

I didn't find anything in examples, readme or any documentation. I think you could add an exemple or add something in the sample, so other people can figure them out. I even thought for a second your library didn't have groupBy.

**Comment by passsy** [comment]
Released in 0.8.0
