### ISSUE TITLE
Sorting by an int, double etc

### ISSUE THREAD

**Issue by mdr** [passsy/kt.dart#111]
I get a compilation error when trying to sort by a property for a int, double, etc:

```
listOf(1, 2, 3).sortedBy((n) => n);
```

The compiler error is:

```
error: Couldn't infer type parameter 'R extends Comparable<R>'.

Tried to infer 'int' for 'R extends Comparable<R>' which doesn't work:
  Type parameter 'R extends Comparable<R>' declared to extend 'Comparable<int>'.
The type 'int' was inferred from:
  Parameter 'selector' declared as     'R Function(int)'
                       but argument is 'int Function(int)'.

Consider passing explicit type argument(s) to the generic.
```

Could this be fixed by changing the generic parameter bound to `R extends Comparable`?

**Comment by passsy** [comment]
You're right I should simply use `Comparable` instead of `R extends Comparable<R>`.

As a workaround you can specify the type `num` explicitly which is a `Comparable<num>`

```dart
listOf(1, 2, 3).sortedBy<num>((n) => n);
```

**Comment by mdr** [comment]
👍 Thanks!
