### ISSUE TITLE
kt.dart exposes no easy way to add an Element to a Set (with a method that returns a set)

### ISSUE THREAD

**Issue by JSANL** [passsy/kt.dart#123]
The current "easiest" way is either `KtSet.from({…set.iter, element}) ` or `set.plusElement(element).toSet()`. 

I don't know the kotlin conventions but an `.add` method would be way more intuitive for me.

**Comment by passsy** [comment]
Released `kt_dart: ^0.8.0-dev.1`

`set.plusElement(element)` now returns `KtSet`
