### ISSUE TITLE
filterNotNull() doesn't change type to non nullable list

### ISSUE THREAD

**Issue by luckyhandler** [passsy/kt.dart#144]
I have the following scenario. 

Actual:
I get a `KtList<T?> objects` 
I run the following code `final KtList<T> nonNullObjects = objects.filterNotNull();`

The dart type check still requires me to use a nullable `T?` type instead of a non-nullable one

Expect:
`filterNotNull()` also changes the returned type to `T` and doesn't require me to continue working with `T?`

**Comment by passsy** [comment]
That's an oversight, wanna create a PR?

**Comment by HideakiSago** [comment]
This is a suggestion.
```
extension NullableKtIterableExtension<T> on KtIterable<T?> {
  KtList<T> filterNotNull() {
    final list = filterNotNullTo(mutableListOf<T>());
    return list;
  }
}
```

I want mapNotNull to be fixed as well.
