### ISSUE TITLE
Add minOrNull()

### ISSUE THREAD

**Issue by passsy** [passsy/kt.dart#155]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/min-or-null.html

**Comment by Anas35** [comment]
The `min()` and `max()` function which is already implemented, has been deprecated in favor of new name `minOrNull()` and `maxOrNull()`. Should we create a new function as `minOrNull()` with same implementation of `min()` and Deprecated the `min()` function ?

**Comment by passsy** [comment]
Exactly. Then we should also deprecate the min/max functions when introducing minOrNull/maxOrNull
