### ISSUE TITLE
toDoubleOrNull and toIntOrNull

### ISSUE THREAD

**Issue by hugobrancowb** [passsy/kt.dart#186]
Do we want these methods into kt.dart? I could easily do them :)

[toDoubleOrNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-int-or-null.html) | [toIntOrNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-double-or-null.html)

**Comment by passsy** [comment]
Thanks for pointing out those missing methods.

It's my fault that I haven't documented it somewhere, but `kt_dart` always tried not to ship extensions for `dart:core` types. There are some general extensions on `T` in [`standard.dart`](https://github.com/passsy/kt.dart/blob/64323fc56ff63f026e169ec9ea6d9c68529551ea/lib/standard.dart#L24) and conversion methods from and to `kt_dart` types. But no extensions for `String`, `int`... 

The correct place for those extensions would be [dartx](https://github.com/leisim/dartx/) which is fully compatible with `kt_dart`, meaning there are no naming clashes.

[toIntOrNull](https://github.com/leisim/dartx/#tointornull) and [toDoubleOrNull](https://github.com/leisim/dartx/#todoubleornull) already exist there.
