### ISSUE TITLE
KtMap forEach() method is missing

### ISSUE THREAD

**Issue by acherkashyn** [passsy/kt.dart#77]
KtMap and KtMutableMap are missing a **forEach( key, value -> {} )** method in Kotlin's Map class.

**Comment by acherkashyn** [comment]
The same can be achieved by getting a set of entries and running forEach on those:
`ktMap.entries.forEach( (entry) { print(entry.key + ', ' + entry.value); } );`, that is a bit verbose. It would be great to be able to write:
`ktMap.forEach( (key, value) { print(key + ', ' + value); } );`

**Comment by acherkashyn** [comment]
Fixed in https://github.com/passsy/kt.dart/pull/78

**Comment by passsy** [comment]
Absolutely! I totally missed many extensions for `KtMap`. Like `flatmap`, `map`, `minWith`, `none` and many more. I'm happy to accept your PRs.
