### ISSUE TITLE
KtMap.map(MapEntry<K, V> -> R) : KtList<R>

### ISSUE THREAD

**Issue by passsy** [passsy/kt.dart#79]
Kotlin allows mapping of entries in a map using `.map`

```kt
mapOf(1 to "foo", 2 to "bar")
        .map { "${it.key} -> ${it.value}" }
        .forEach(::print)
// 1 -> foo
// 2 -> bar
```

This leads to a name clash with `KtMap.map` which returns the Dart `Map`.

Currently all *kt.dart* collections allow access to the dart equivalents. 

```
KtIterable.iter -> Iterable
KtList.list -> List
KtMap.map -> Map
KtSet.set -> Set
```

We have to find a way to provide standardized ways to access the dart equivalents. Additionally we should make it as easy as possible to make kt.dart collections useable using for loops.

```dart
// kt.dart 0.5.0
for(final i in listOf(1, 2, 3).iter) {
  print(i);
}
```

**Comment by passsy** [comment]
One way of solving it would be to convert the interop properties to functions called `asMap()`, `asList()`, `asSet()` and `asList()`.

But this would clash with the existing `KtIterable<T>.asIterable(): KtIterable<T>`

And for loops would look even worse

```dart
for(final i in listOf(1, 2, 3).asIterable()) {
  print(i);
}
```

**Comment by passsy** [comment]
On could name the `map` function `mapEntries` and avoid naming collisions

**Comment by passsy** [comment]
`mapEntries()` wouldn't be a great solution because it wouldn't be consistent with `mapNotNull()`

**Comment by jerolimov** [comment]
From other languages I would expect that `KtMap.map` is a mapping function similar to your first Kotlin example. This is also the behaviour in the Dart List:

```dart
void main() {
  [1, 2, 3, 4, 5]
    .map((i) => i * 2)
    .forEach(print);
}
```

I would prefer if the methods to get the standard Dart object would be renamed to `asList`, `asMap`, ... or `toList`, `toMap`.

I didn't yet understand the problem with `asIterable`. Why is this required in this example? Shouldn't the KtList implements Iterable already?

```dart
for(final i in listOf(1, 2, 3).asIterable()) {
  print(i);
}
```

**Comment by passsy** [comment]
Context why `KtList` does not implement `Iterable` and instead offers a `.iter` property.
https://github.com/dart-lang/language/issues/226

**Comment by jerolimov** [comment]
Okay, thanks for the context. I understand now that the [Iterable](https://api.dartlang.org/stable/2.1.1/dart-core/Iterable-class.html) interface is much bigger than expected..

With this step back, I didn't see a big point why a map method is needed. Esp. mapping over a map is always a little bit tricky. Are the code maps over the key or values or both?

Readable code is so important, that I think its also great that KtMap has already the options to map over the keys, values and entries with `map.keys.map()`, etc.. Right? Maybe you can push the documentation or example into this direction and show the benefits of this.

```dart
mapFrom({ "a": 1, "b": 2, "sum", 3 })
  .entries
  .where(entry => entry.key != name)
  .map(entry => entry.value)
  .map(value => value * 2)
  .forEach(print);
```

Hopefully you will get some other feedback as well 😏
