### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by votruk** [passsy/kt.dart#93]
I develop an app that involves massive working with lists. One of the popular features that I use is list shuffling.

As I see there is no such a method in this library yet. It is very frustrating to switch to standard dart collections to just shuffle and then go back to kt.dart which is awesome btw.

Do you have plans to implement this functionality?

**Comment by passsy** [comment]
Very reasonable. I'd be happy to receive a PR from you :)

**Comment by votruk** [comment]
I'll try!
What is the process? Fork your repo and make a PR? To master branch or not? Some info about how to do it would be really helpful :)

**Comment by passsy** [comment]
Here are some hopefully helpful sources:
- https://github.com/firstcontributions/first-contributions
- http://makeapullrequest.com/

Create a PR to `master`. Make the change as small as possible and try to be consistent with the rest of the project.

Have fun!

**Comment by votruk** [comment]
I've created a pull request: https://github.com/passsy/kt.dart/pull/99
Is it ok? Do I need to add something else?

**Comment by passsy** [comment]
Thank you very much!
